CREATE OR REPLACE TABLE IOT_SENSOR_DATA (
    TIMESTAMP STRING,
    SENSOR_ID INT,
    TEMPERATURE_CELSIUS FLOAT,
    TEMPERATURE_FAHRENHEIT FLOAT,
    HUMIDITY_PERCENTAGE FLOAT,
    PRESSURE FLOAT
);
